name: doctor_finder_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7

  # UI dependencies
  cupertino_icons: ^1.0.8

  # Location and maps
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0
  permission_handler: ^12.0.0

  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.3.1
  flutter_email_sender: ^7.0.0
  logging: ^1.2.0  # ADDED THIS LINE

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true